language: bash

env:
  - SHUNIT_COLOR='always'

script:
  # Execute the unit tests.
  - ./test_runner

addons:
  apt:
    packages:
      - ksh
      - mksh
      - zsh

matrix:
  include:
    - os: linux
      dist: bionic  # Support Ubuntu Bionic 18.04 through at least Apr 2023.
    - os: linux
      dist: xenial  # Support Ubuntu Xenial 16.04 through at least Apr 2021.
    - os: linux
      dist: trusty  # Support Ubuntu Trusty 14.04 through at least Apr 2019.
    - os: osx
    - os: linux
      script:
        # Run the source through ShellCheck (http://www.shellcheck.net).
        - shellcheck shunit2 *_test.sh
        - shellcheck -s sh shunit2_test_helpers

branches:
  only:
  - master
  - 2.1.x
  # Tags, e.g. v.2.1.8.
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
